Repository NLog/NLog.Windows.Forms, pull requests merged in 2022-05, with the labels that each got.

#104 Fixed obsolete warning in MessageBoxTarget that blocks for NLog 5
  NLog.Windows.Forms/MessageBoxTarget.cs
  NLog.Windows.Forms/NLog.Windows.Forms.csproj
  appveyor.yml
  build.ps1
Labels: size/S, build

#109 Added .NET 6 example
  NLog.Windows.Forms.sln
  TestApplicationNet6/TestApplicationNet6.csproj
  appveyor.yml
Labels: size/M

#114 Move files and change namespaces
  NLog.Windows.Forms.Tests/RichTextBoxTargetTests.cs
  NLog.Windows.Forms.Tests/ToolStripItemTargetTests.cs
  NLog.Windows.Forms.sln
  NLog.Windows.Forms/LayoutRenderers/RichTextBoxLinkLayoutRenderer .cs
  NLog.Windows.Forms/NLog.Windows.Forms.csproj
  NLog.Windows.Forms/NLog.Windows.Forms.csproj.DotSettings
  NLog.Windows.Forms/Targets/FormControlTarget.cs
  NLog.Windows.Forms/Targets/Helpers/FormHelper.cs
  NLog.Windows.Forms/Targets/MessageBoxTarget.cs
  NLog.Windows.Forms/Targets/RichTextBoxRowColoringRule.cs
  NLog.Windows.Forms/Targets/RichTextBoxTarget.cs
  NLog.Windows.Forms/Targets/RichTextBoxTargetMessageRetentionStrategy.cs
  NLog.Windows.Forms/Targets/RichTextBoxWordColoringRule.cs
  NLog.Windows.Forms/Targets/ToolStripItemTarget.cs
  TestApplications/TestApplication.Shared/Form1.Designer.cs
  TestApplications/TestApplication.Shared/Form1.cs
  TestApplications/TestApplication.Shared/Form1.resx
  TestApplications/TestApplication.Shared/NLog.xsd
  TestApplications/TestApplication.Shared/Program.cs
  TestApplications/TestApplication.Shared/TestApplication.Shared.csproj
  TestApplications/TestApplication.Shared/nlog.config
  TestApplications/TestApplicationCore3/TestApplicationCore3.csproj
  TestApplications/TestApplicationNet5/TestApplicationNet5.csproj
  TestApplications/TestApplicationNet6/TestApplicationNet6.csproj
  TestApplications/TestApplicationNetFramework/App.config
  TestApplications/TestApplicationNetFramework/Properties/AssemblyInfo.cs
  TestApplications/TestApplicationNetFramework/Properties/Resources.Designer.cs
  TestApplications/TestApplicationNetFramework/Properties/Resources.resx
  TestApplications/TestApplicationNetFramework/Properties/Settings.Designer.cs
  TestApplications/TestApplicationNetFramework/Properties/Settings.settings
  TestApplications/TestApplicationNetFramework/TestApplicationNetFramework.csproj
Labels: size/M, breaking change

#115 Remove referenced assemblies for .NET and .NET Core
  NLog.Windows.Forms.Tests/NLog.Windows.Forms.Tests.csproj
  NLog.Windows.Forms/NLog.Windows.Forms.csproj
Labels: size/L

#117 Remove LINKS_SUPPORTED symbol
  NLog.Windows.Forms.Tests/NLog.Windows.Forms.Tests.csproj
  NLog.Windows.Forms.Tests/RichTextBoxTargetTests.cs
  NLog.Windows.Forms/LayoutRenderers/RichTextBoxLinkLayoutRenderer .cs
  NLog.Windows.Forms/NLog.Windows.Forms.csproj
  NLog.Windows.Forms/Targets/RichTextBoxTarget.cs
Labels: size/M

#118 Support Layoutable Properties
  NLog.Windows.Forms.Tests/RichTextBoxTargetTests.cs
  NLog.Windows.Forms/Targets/FormControlTarget.cs
  NLog.Windows.Forms/Targets/RichTextBoxRowColoringRule.cs
  NLog.Windows.Forms/Targets/RichTextBoxTarget.cs
  NLog.Windows.Forms/Targets/RichTextBoxWordColoringRule.cs
  NLog.Windows.Forms/Targets/ToolStripItemTarget.cs
Labels: size/L
